# Generated by Django 2.0 on 2017-12-14 00:49

from django.db import migrations
from hfapp.constants import COLOR

def define_colors(apps, schema_editor):
#{
    # We can't import the Color model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Color = apps.get_model('hfapp', 'Color')
    
    Color(name=COLOR.RED).save()
    Color(name=COLOR.GREEN).save()
    Color(name=COLOR.BLUE).save()
    Color(name=COLOR.COLORLESS).save()
#}

class Migration(migrations.Migration):

    dependencies = [
        ('hfapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(define_colors)
    ]
