# Generated by Django 2.0 on 2017-12-14 00:49

from django.db import migrations

def define_colors(apps, schema_editor):
#{
    # We can't import the Color model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Color = apps.get_model('hfapp', 'Color')
    
    Color(name='red').save()
    Color(name='green').save()
    Color(name='blue').save()
    Color(name='colorless').save()
#}

class Migration(migrations.Migration):

    dependencies = [
        ('hfapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(define_colors)
    ]
