# Generated by Django 2.0 on 2017-12-16 00:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hfapp.models.validators

def empty_colors(apps, schema_editor):
#{
    Color = apps.get_model('hfapp', 'Color')
    Color.objects.all().delete()
#}

class Migration(migrations.Migration):

    dependencies = [
        ('hfapp', '0002_auto_20171213_1649'),
    ]

    operations = [
        migrations.RunPython(empty_colors),
        migrations.CreateModel(
            name='WeaponGroup',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('range', models.PositiveSmallIntegerField(validators=[hfapp.models.validators.InListValidator([1, 2], code='validate_range')])),
                ('vs_stat', models.CharField(max_length=3, validators=[hfapp.models.validators.InListValidator(('Def', 'Atk', 'Spd', 'Res', 'HP'), code='validate_stat')])),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='id',
            # field=models.CharField(default=django.utils.timezone.now, max_length=2, primary_key=True, serialize=False),
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weapon_types_of_color', to='hfapp.Color'),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hfapp.WeaponGroup'),
        ),
    ]
