# Generated by Django 2.0 on 2017-12-16 01:09

from django.db import migrations, models
import django.db.models.deletion
import hfapp.models.validators

def data_migration(apps, schema_editor):
#{
    SkillType = apps.get_model('hfapp', 'SkillType')
    
    SkillType(id='1Wp', name='Weapon').save()
    SkillType(id='2Su', name='Support').save()
    SkillType(id='3Sp', name='Special').save()
    SkillType(id='4A', name='A').save()
    SkillType(id='5B', name='B').save()
    SkillType(id='6C', name='C').save()
    SkillType(id='7S', name='Seal').save()
#}

class Migration(migrations.Migration):

    dependencies = [
        ('hfapp', '0004_auto_20171215_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('inheritable', models.BooleanField(default=True)),
                ('prerequisite', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prerequisite_for', to='hfapp.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='vs_stat',
            field=models.CharField(max_length=3, validators=[hfapp.models.validators.InListValidator(('Atk', 'Res', 'HP', 'Spd', 'Def'), code='validate_stat')]),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills_of_type', to='hfapp.SkillType'),
        ),
        migrations.AddField(
            model_name='skill',
            name='weapon_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weapons_of_type', to='hfapp.WeaponType'),
        ),
        migrations.RunPython(data_migration)
    ]
