# Generated by Django 2.0 on 2017-12-20 17:20

from django.db import migrations, models
import hfapp.models.validators
import hfapp.models as models

def data_migration(apps, schema_editor):
#{
    # This is probably horrible
    
    if not models.WeaponType.objects.exists():
        models.WeaponType.objects.bulk_create([
            models.WeaponType(id='Sw', name='Sword',        group=models.WeaponGroup.SWORD,  color=models.Color.RED,       range=1, vs_stat='Def'),
            models.WeaponType(id='La', name='Lance',        group=models.WeaponGroup.LANCE,  color=models.Color.BLUE,      range=1, vs_stat='Def'),
            models.WeaponType(id='Ax', name='Axe',          group=models.WeaponGroup.AXE,    color=models.Color.GREEN,     range=1, vs_stat='Def'),
            models.WeaponType(id='Bw', name='Bow',          group=models.WeaponGroup.BOW,    color=models.Color.COLORLESS, range=2, vs_stat='Def'),
            models.WeaponType(id='Dg', name='Dagger',       group=models.WeaponGroup.DAGGER, color=models.Color.COLORLESS, range=2, vs_stat='Def'),
            models.WeaponType(id='RT', name='Red Tome',     group=models.WeaponGroup.TOME,   color=models.Color.RED,       range=2, vs_stat='Res'),
            models.WeaponType(id='BT', name='Blue Tome',    group=models.WeaponGroup.TOME,   color=models.Color.BLUE,      range=2, vs_stat='Res'),
            models.WeaponType(id='GT', name='Green Tome',   group=models.WeaponGroup.TOME,   color=models.Color.GREEN,     range=2, vs_stat='Res'),
            models.WeaponType(id='St', name='Staff',        group=models.WeaponGroup.STAFF,  color=models.Color.COLORLESS, range=2, vs_stat='Res'),
            models.WeaponType(id='RB', name='Red Breath',   group=models.WeaponGroup.BREATH, color=models.Color.RED,       range=1, vs_stat='Res'),
            models.WeaponType(id='BB', name='Blue Breath',  group=models.WeaponGroup.BREATH, color=models.Color.BLUE,      range=1, vs_stat='Res'),
            models.WeaponType(id='GB', name='Green Breath', group=models.WeaponGroup.BREATH, color=models.Color.GREEN,     range=1, vs_stat='Res')
        ])
#}


class Migration(migrations.Migration):

    dependencies = [
        ('hfapp', '0005_auto_20171215_1709'),
    ]

    operations = [
        migrations.RunPython(data_migration)
    ]
